www/service/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('www.service.views',

                       url(r'^$', 'service_list'),
                       url(r'^(?P<service_id>\d+)$', 'service_detail'),
                       url(r'^product/(?P<product_id>\d+)$', 'product_detail'),
                       url(r'^my_order$', 'my_order'),
                       url(r'^my_zan$', 'my_zan'),
                       url(r'^add_zan$', 'add_zan'),
                       url(r'^cancel_zan$', 'cancel_zan'),
                       url(r'^create_order$', 'create_order'),

                       url(r'^success$', 'success'),
                       url(r'^error$', 'error'),
                       )

www/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic.simple import direct_to_template


urlpatterns = patterns('',
                       url(r'^login_weixin$', 'www.account.views.login_weixin'),
                       url(r'^login$', 'www.account.views.login'),
                       url(r'^get_weixin_login_state$', 'www.account.views.get_weixin_login_state'),
                       url(r'^logout$', 'www.account.views.logout'),
                       url(r'^qiniu_img_return$', 'www.misc.views.qiniu_img_return'),
                       url(r'^save_img$', 'www.misc.views.save_img'),
                       url(r'^neice$', 'www.account.views.neice'),

                       url(r'^$', 'www.service.views.index'),
                       url(r'^admin/', include('www.admin.urls')),
                       url(r'^account/', include('www.account.urls')),
                       url(r'^weixin/', include('www.weixin.urls')),
                       url(r'^service/', include('www.service.urls')),
                       url(r'^kind/(?P<kind_id>\d+)$', 'www.service.views.service_list'),

                       url(r'^(?P<txt_file_name>\w+)\.txt$', 'www.misc.views.txt_view'),
                       url(r'^s/(?P<template_name>.*)$', 'www.misc.views.static_view'),
                       url(r'^500$', 'www.misc.views.test500'),
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
                       url(r'^crossdomain.xml$', direct_to_template, {'template': 'crossdomain.xml'}),
                       )

# urlpatterns += patterns('misc.views_paycallback',
#                         (r'^alipaycallback$', 'alipaycallback'),
#                         (r'^alipaynotify$', 'alipaynotify'),
#                         (r'^weixinnotify$', 'weixinnotify'),
#                         (r'^weixin_success_info$', 'weixin_success_info'),
#                         (r'^weixinwarning$', 'weixinwarning'),

#                         (r'^test_paycallback$', 'test_paycallback'),
#                         )

www/service/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings


class Kind(models.Model):
    '''
    @note: 类别
    '''
    kind_type_choices = ((0, u"餐饮福利"), (1, u"员工活动"), (2, u"宣传物料"), (3, u"日常办公"), (4, u"公司代办"), (5, u"其他"))

    name = models.CharField(verbose_name=u"名称", max_length=32, unique=True)
    slogan = models.CharField(verbose_name=u"slogan", max_length=256)
    kind_type = models.IntegerField(verbose_name=u"类别", default=0, choices=kind_type_choices)

    hot = models.IntegerField(verbose_name=u"热度", default=0)
    state = models.BooleanField(verbose_name=u"状态是否正常", default=True)
    sort = models.IntegerField(verbose_name=u"排序", default=0)
    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["sort", "create_time"]

    def get_url(self):
        return u'/kind/%s' % self.id

    def get_full_url(self):
        return u'%s%s' % (settings.MAIN_DOMAIN, self.get_url())


class KindOpenInfo(models.Model):
    '''
    @note: 类别开放信息
    '''
    kind = models.ForeignKey("Kind")
    city_id = models.IntegerField(verbose_name=u"所属城市")
    open_time = models.DateTimeField(verbose_name=u"开放时间",  db_index=True)

    class Meta:
        unique_together = [("kind", "city_id"), ]
        ordering = ["-open_time"]


class Service(models.Model):
    '''
    @note: 服务商
    '''
    level_choices = ((0, u"普通"), (1, u"自营"), (2, u"优质"))

    name = models.CharField(verbose_name=u"名称", max_length=32, db_index=True)
    kind = models.ForeignKey("Kind")
    logo = models.CharField(verbose_name=u"logo", max_length=256)
    city_id = models.IntegerField(verbose_name=u"所属城市")
    summary = models.CharField(verbose_name=u"摘要", max_length=256)
    des = models.TextField(verbose_name=u"简介")
    imgs = models.TextField(verbose_name=u"轮播图集中存放")

    service_area = models.CharField(verbose_name=u"覆盖区域", max_length=256)
    tel = models.CharField(verbose_name=u"联系电话", max_length=256, null=True)
    addr = models.CharField(verbose_name=u"地址", max_length=256, null=True)
    longitude = models.CharField(verbose_name=u"经度", max_length=32, null=True)
    latitude = models.CharField(verbose_name=u"纬度", max_length=32, null=True)
    join_time = models.DateTimeField(verbose_name=u"入驻时间", db_index=True, null=True)

    recommend_user_id = models.CharField(verbose_name=u"推荐人", max_length=32, db_index=True, null=True)
    recommend_des = models.TextField(verbose_name=u"推荐语", null=True)
    zan_count = models.IntegerField(verbose_name=u"点赞次数", default=0, db_index=True)
    order_count = models.IntegerField(verbose_name=u"预订次数", default=0, db_index=True)
    level = models.IntegerField(verbose_name=u"供应商等级", default=0, choices=level_choices)
    is_show = models.BooleanField(verbose_name=u"是否在列表页显示", default=True)
    state = models.BooleanField(verbose_name=u"状态是否正常", default=True)
    sort = models.IntegerField(verbose_name=u"排序", default=0)
    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["sort", "create_time"]
        unique_together = [("kind", "name"), ]

    def get_tel(self):
        return self.tel or "4008-920-310"

    def get_url(self):
        return u'/service/%s' % self.id

    def get_covers(self):
        import re
        return re.compile('<img .*?src=[\"\'](.+?)[\"\']').findall(self.imgs)

    def get_format_des(self):
        des = ""

        for x in self.des.split('\r\n'):
            des += "<p>%s</p>" % x

        return des
        # return self.des.replace('\r\n', '<br/>')


class Product(models.Model):
    '''
    @note: 产品
    '''
    name = models.CharField(verbose_name=u"名称", max_length=32, db_index=True)
    service = models.ForeignKey("Service")
    cover = models.CharField(verbose_name=u"封面", max_length=256, null=True)
    summary = models.TextField(verbose_name=u"摘要信息", null=True)
    des = models.TextField(verbose_name=u"简介")
    price = models.DecimalField(verbose_name=u"价格", max_digits=20, decimal_places=2, db_index=True)
    params = models.TextField(verbose_name=u"额外参数", null=True)

    state = models.BooleanField(verbose_name=u"状态是否正常", default=True)
    sort = models.IntegerField(verbose_name=u"排序", default=0)
    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["sort", "-create_time"]
        unique_together = [("name", "service"), ]

    def get_url(self):
        return u'/service/product/%s' % self.id


class Order(models.Model):
    '''
    @note: 预约订单
    '''
    state_choices = ((0, u"待处理"), (1, u"接单中"), (2, u"已完成"))

    user_id = models.CharField(max_length=32, db_index=True)
    service = models.ForeignKey("Service")
    product = models.ForeignKey("Product", null=True)   # 产品字段为空表示直接预约供应商

    price = models.DecimalField(verbose_name=u"价格", max_digits=20, decimal_places=2, db_index=True)
    state = models.IntegerField(verbose_name=u"状态是否正常", default=0, choices=state_choices)
    sort = models.IntegerField(verbose_name=u"排序", default=0)
    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    class Meta:
        ordering = ["sort", "-create_time"]


class Zan(models.Model):
    '''
    @note: 赞过的供应商，用于收藏
    '''
    user_id = models.CharField(max_length=32, db_index=True)
    service = models.ForeignKey("Service")

    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    class Meta:
        unique_together = [("user_id", "service"), ]
        ordering = ["-id"]


class Company(models.Model):

    '''
    公司信息
    '''
    state_choices = ((0, u"停用"), (1, u"正常"))

    name = models.CharField(verbose_name=u"名称", max_length=128, unique=True)
    short_name = models.CharField(verbose_name=u"简称", max_length=128, null=True)
    logo = models.CharField(verbose_name=u"logo", max_length=256, null=True)
    des = models.TextField(verbose_name=u"简介", null=True)
    staff_name = models.CharField(verbose_name=u"企业联系人", max_length=16, null=True)
    mobile = models.CharField(verbose_name=u"手机", max_length=32, null=True)
    tel = models.CharField(verbose_name=u"座机", max_length=32, null=True)
    addr = models.CharField(verbose_name=u"地址", max_length=256, null=True)
    person_count = models.IntegerField(verbose_name=u"员工总数", default=0)
    city_id = models.IntegerField(verbose_name=u"所属城市", default=0)
    state = models.IntegerField(verbose_name=u"状态", default=1, db_index=True, choices=state_choices)
    sort = models.IntegerField(verbose_name=u"排序", default=0)
    create_time = models.DateTimeField(verbose_name=u"创建时间", auto_now_add=True, db_index=True)

    def get_logo(self):
        return self.logo if self.logo else '%simg/logo.png' % settings.MEDIA_URL

    def combine_name(self):
        '''
        组合名字：
        成都乐动科技有点公司 [ 咕咚 ]
        '''
        return '%s [ %s ]' % (self.name, self.short_name or '-')

    class Meta:
        ordering = ["sort", "-create_time"]


class CompanyManager(models.Model):
    company = models.ForeignKey("Company")
    user_id = models.CharField(verbose_name=u"管理员id", max_length=32, db_index=True)
    role = models.IntegerField(verbose_name=u"角色", default=0, db_index=True)

    class Meta:
        unique_together = [("company", "user_id"), ]
        ordering = ["company"]

class CashAccount(models.Model):

    '''
    @note: 现金账户
    '''
    company = models.ForeignKey("Company", unique=True)
    balance = models.DecimalField(verbose_name=u"最新余额", max_digits=20, decimal_places=2, default=0, db_index=True)
    max_overdraft = models.DecimalField(verbose_name=u"最大透支额", max_digits=20, decimal_places=2, default=1000, db_index=True)

    class Meta:
        ordering = ['balance', 'id']

class CashRecord(models.Model):

    '''
    @note: 现金账户流水
    '''
    operation_choices = ((0, u"充值"), (1, u"消费"))

    cash_account = models.ForeignKey("CashAccount")
    value = models.DecimalField(verbose_name=u"操作金额", max_digits=20, decimal_places=2, db_index=True)
    current_balance = models.DecimalField(verbose_name=u"当时余额", max_digits=20, decimal_places=2, db_index=True)
    operation = models.IntegerField(verbose_name=u"操作类型", choices=operation_choices, db_index=True)
    notes = models.CharField(verbose_name=u"备注", max_length=256)
    is_invoice = models.IntegerField(verbose_name=u"是否记录开票金额", default=1, null=True, db_index=True)
    ip = models.CharField(verbose_name=u"ip", max_length=32, null=True)
    create_time = models.DateTimeField(verbose_name=u"流水时间", auto_now_add=True, db_index=True) 

    class Meta:
        ordering = ['-id']


class ServiceCashAccount(models.Model):

    '''
    @note: 供货商现金账户
    '''
    service = models.ForeignKey("Service", unique=True)
    balance = models.DecimalField(verbose_name=u"最新余额", max_digits=20, decimal_places=2, default=0, db_index=True)

    class Meta:
        ordering = ['-balance', 'id']


class ServiceCashRecord(models.Model):

    '''
    @note: 供货商现金账户流水
    '''
    operation_choices = ((0, u"入账"), (1, u"转出"))

    cash_account = models.ForeignKey("ServiceCashAccount")
    value = models.DecimalField(verbose_name=u"操作金额", max_digits=20, decimal_places=2, db_index=True)
    current_balance = models.DecimalField(verbose_name=u"当时余额", max_digits=20, decimal_places=2, db_index=True)
    operation = models.IntegerField(verbose_name=u"操作类型", choices=operation_choices, db_index=True)
    notes = models.CharField(verbose_name=u"备注", max_length=256)
    ip = models.CharField(verbose_name=u"ip", max_length=32, null=True)
    order_id = models.CharField(verbose_name=u"订单流水id", max_length=32, null=True)
    create_time = models.DateTimeField(verbose_name=u"流水时间", auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-id']



class OrderRecord(models.Model):

    '''
    '''
    state_choices = ((0, u"准备中"), (1, u"已完成"), (2, u"作废"))

www/service/views.py
# -*- coding: utf-8 -*-

import json
import time
import datetime

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import RequestContext
from django.shortcuts import render_to_response

from common import utils, page
from misc.decorators import common_ajax_response, member_required, request_limit_by_ip, auto_select_template

from www.account.interface import UserBase, VerifyInfoBase
from www.service.interface import KindBase, ServiceBase, ProductBase, ZanBase, OrderBase
from www.weixin.interface import WeixinBase, Sign


kb = KindBase()
sb = ServiceBase()
zb = ZanBase()


@auto_select_template
def index(request, template_name='mobile/index.html'):
    city_id = request.session.get("city_id", 1974)
    data = kb.get_kind_list(city_id=city_id)

    # 转换成json
    data_json = json.dumps(data)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def service_list(request, kind_id, template_name='mobile/service/service_list.html'):

    kind = kb.get_kind_by_id(kind_id)

    _services = sb.get_service_by_kind(kind_id)
    services = []
    for i in range(_services.count()):
        temp = _services[i]
        setattr(temp, 'delays', 0.2 + i * 0.1)
        services.append(temp)

    last_delay = 0.2 + len(services) * 0.1

    # 如果服务商数量少于2显示 即将开放
    show_comingsoon = True if len(services) <= 2 else False

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def service_detail(request, service_id, template_name='mobile/service/service_detail.html'):
    service = sb.get_service_by_id(service_id)

    if not service:
        raise Http404

    # 推荐用户
    if service.recommend_user_id:
        recommend_user = UserBase().get_user_by_id(service.recommend_user_id)
        recommend_user_info = dict(avatar=recommend_user.get_avatar_65, name=recommend_user.nick)
        verify_info = VerifyInfoBase().get_info_by_user_id(recommend_user.id)
        if verify_info:
            recommend_user_info.update(name=verify_info.name, title=verify_info.title, company_name=verify_info.get_short_name())

    # 产品列表
    products = ProductBase().get_products_by_service(service)

    # 是否赞过
    is_zan = ZanBase().is_zan(service_id, request.user.id)

    # 是否验证用户
    verify_user = VerifyInfoBase().get_info_by_user_id(request.user.id)
    is_verify = '0' if not verify_user else '1'

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


def product_detail(request, product_id, template_name='mobile/service/product_detail.html'):
    product = ProductBase().get_product_by_id(product_id)

    if not product:
        raise Http404
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


@member_required
def my_order(request, template_name='mobile/service/my_order.html'):
    orders = OrderBase().get_order_by_user_id(request.user.id)

    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


@member_required
def my_zan(request, template_name='mobile/service/my_zan.html'):
    zans = zb.get_zan_by_user_id(request.user.id)
    return render_to_response(template_name, locals(), context_instance=RequestContext(request))


# ===================================================ajax部分=================================================================#

@member_required
@common_ajax_response
def add_zan(request):
    service_id = request.REQUEST.get('service_id')
    return zb.add_zan(request.user.id, service_id)


@member_required
@common_ajax_response
def cancel_zan(request):
    service_id = request.REQUEST.get('service_id')
    return zb.cancel_zan(request.user.id, service_id)


@member_required
@common_ajax_response
def create_order(request):

    service_id = request.REQUEST.get('service_id')

    code, msg = OrderBase().create_order(request.user.id, service_id)

    return code, '' if code == 0 else msg

www/templates/mobile/service/my_order.html
{% extends "mobile/base_home.html" %}
{% block title %}我的预约{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/animate/animate.min.css">
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/site/account/my_order.css?v={{MEDIA_VERSION}}">
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function(){

    });
</script>
{% endblock %}

{% block back_url %}/account/profile{% endblock %}

{% block container %}
<div class="row ml-0 mr-0 pt-20">
    {% if not orders %}
    <div class="col-xs-12 pr">
        <div class="col-xs-12 rectangle-1 pt-3">
            <span class="circle-1"></span>
            <div class="col-xs-12 pl-70 pt-20">
                <div class="rectangle-3"></div>
            </div>
            <div class="col-xs-12 pl-70 pt-8">
                <div class="rectangle-4"></div>
                <div class="rectangle-4"></div>
            </div>
        </div>
        <div class="col-xs-12 rectangle-2"></div>
        <div class="col-xs-12 text-center pt-50">
            <a class="btn btn-default btn-booking" value="" href="/">
                <span>立即预约</span>
                <img class="person" src="{{MEDIA_URL}}img/profile/person.png">
                <span class="txt">还没有预约服务?</span>
            </a>
        </div>
    </div>
    {% else %}
    <div class="col-xs-12 pl-20 pr-20">
        {% for order in orders %}
        <ul class="list-group col-xs-12 pl-15 pr-15">
            <div class="col-xs-12 service">
                <span class="bg-curtain bg-curtain-0"></span>
                <img class="avatar" src="{{order.service.logo}}">
                <div class="col-xs-12 f17 pr-5 pt-10">
                    <span class="co-222222">{{order.service.name}}</span>
                    <span class="f12 pull-right co-b6b6b6 pt-3">{{order.create_time|date:'Y-m-d H:m'}}</span>
                </div>
                <div class="col-xs-12 f12 co-b6b6b6 pt-3 pr-5 pb-15">
                    <span class="tag">{{order.service.kind.name}}</span>
                    {% if order.state == 0 %}
                    <span class="pull-right pt-5 f13 co-f0ad4e"><i class="fa fa-hourglass-2 pr-3"></i>{{order.get_state_display}}</span>
                    {% elif order.state == 1 %}
                    <span class="pull-right pt-5 f13 co-5bc0de"><i class="fa fa-cogs pr-3"></i>{{order.get_state_display}}</span>
                    {% elif order.state == 2 %}
                    <span class="pull-right pt-5 f13 co-5cb85c"><i class="fa fa-check pr-3"></i>{{order.get_state_display}}</span>
                    {% endif %}
                </div>
            </div>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

www/templates/mobile/service/my_zan.html
{% extends "mobile/base_home.html" %}
{% block title %}我赞过的{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/animate/animate.min.css">
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/site/account/my_zan.css?v={{MEDIA_VERSION}}">
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function(){

    });
</script>
{% endblock %}

{% block back_url %}/account/profile{% endblock %}

{% block container %}
<div class="row ml-0 mr-0 pt-15">
    <div class="col-xs-12 pl-20 pr-20">
        {% if not zans %}
         <div class="co-95989d">暂无</div>
        {% else %}
        <ul class="list-group col-xs-12 pr-0 pl-0">
            {% for zan in zans %}
            <a href="{{zan.service.get_url}}">
                <li class="list-group-item col-xs-12 pr-0 pl-0">
                    <div class="col-xs-12 service">
                        <span class="bg-curtain bg-curtain-{{zan.service.kind.kind_type}}"></span>
                        <img class="avatar" src="{{zan.service.logo}}">
                        <div class="col-xs-12 f17 pr-5 pt-10">
                            <span class="co-222222">{{zan.service.name}}</span>
                            <span class="f12 pull-right co-b6b6b6">{{zan.service.zan_count}}人赞过</span>
                        </div>
                        <div class="col-xs-12 f12 co-b6b6b6 pt-5 pr-5 pb-12">
                            <span class="tag">{{zan.service.kind.name}}</span>
                        </div>
                    </div>
            </li>
            </a>
            {% endfor %}
        </ul>
        {% endif %}

    </div>
</div>
{% endblock %}

{% block nav %}{% endblock %}

www/templates/mobile/service/product_detail.html
{% extends "mobile/base_home.html" %}
{% block title %}{{product.name}}{% endblock title %}
{% block css %}
<style type="text/css">
.img-des{
    width: 90px;
    position: absolute;
    left: 15px;
    top: 28px;
    padding: 10px;
    box-shadow: 0px 0px 5px #ffcfa3;
}
.booking{
    position: fixed;
    left: 0;
    bottom: 0;
    width: 100%;
    background-color: #ffffff;
    padding: 15px 5px;
    text-align: center;
}
.btn-booking{
    color: #f07925;
    padding: 3px 40px;
    border-radius: 18px;
    background-color: #fff;
    box-shadow: #ffd5b8 0 2px 4px;
    border: 0;
    font-size: 16px;
}
.des{
    margin-bottom: 20px;
}
.des img{
    width: 100%;
}
.des a{
    background-color: #ff8834;
    color: #fff;
    padding: 8px 12px;
    border-radius: 4px;
}
</style>
{% endblock %}

{% block js %}
<script type="text/javascript">
$(document).ready(function(){

});
</script>
{% endblock %}
{% block back_url %}{{product.service.get_url}}{% endblock %}
{% block container %}
<div class="row ml-0 mr-0">
    <div class="col-xs-12 pl-105 pt-20">
        <img class="img-des" src="{{product.cover}}">
        <div class="col-xs-12 f20 pt-15">{{product.name}}</div>
        <div class="col-xs-12 f12 co-95989d pt-3">{{product.summary}}</div>
        <div class="col-xs-12 co-48494b pt-10">
            <span class="co-ea232a"><i class="fa fa-rmb pr-3"></i>{{product.price}}</span>
        </div>
    </div>
    <div class="col-xs-12 pt-20 pb-10">
        <div class="col-xs-12 border-bottom-1 bdc-eeeeee"></div>
    </div>
    <div class="col-xs-12 des">
        {{product.des|safe}}
    </div>
    <!-- <div class="booking">
        <button class="btn-booking" value="">立即预定</button>
    </div> -->
</div>
{% endblock %}

{% block nav %}{% endblock %}

www/templates/mobile/service/service_list.html
{% extends "mobile/base_home.html" %}
{% block title %}{{kind.name}}服务商{% endblock title %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/animate/animate.min.css">
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}css/site/service_list.css?v={{MEDIA_VERSION}}">
<style type="text/css">
{% if kind.kind_type == 0 %}
body{
    background: linear-gradient(to right, #f68e57, #f9b757);
}
{% elif kind.kind_type == 1 %}
body{
    background: linear-gradient(to right, #ff589c, #ff58c9);
}
{% elif kind.kind_type == 2 %}
body{
    background: linear-gradient(to right, #35d9ae, #29eaa1);
}
{% elif kind.kind_type == 3 %}
body{
    background: linear-gradient(to right, #52a7fe, #4cb8fe);
}
{% elif kind.kind_type == 4 %}
body{
    background: linear-gradient(to right, #05b5e1, #2ad2e8);
}
{% elif kind.kind_type == 5 %}
body{
    background: linear-gradient(to right, #a883fa, #bd90fa);
}
{% endif %}
</style>
{% endblock %}
{% block back_url %}/{% endblock %}
{% block container %}
<div class="row ml-0 mr-0">
    <div class="col-xs-12 co-ffffff pt-35 pb-20 pr">
        <i class="fa fa-quote-left"></i>
        <div class="col-xs-12 pl-20 f13 letter-spacing-1">{{kind.slogan}}</div>
        <div class="col-xs-12 text-right f13 pt-8">——小橙企服</div>
    </div>

    <ul class="list-group col-xs-12 pl-20 pr-20">

        {% for service in services %}
        <a href="{{service.get_url}}" class="list-group-item col-xs-12 pr-0 pl-0 over-flow-hide mb-15 animated fadeInUp" style="animation-delay: {{ service.delays }}s;-webkit-animation-delay: {{  service.delays }}s;">
            <div class="col-xs-12 pl-70 pr-10 pt-0 pb-3 pr h57">
                <span class="bg-curtain bg-curtain-{{kind.kind_type}}"></span>
                <img class="avatar" src="{{service.logo}}">
                <div class="col-xs-12 f17 pr-5">{{service.name}}</div>
                <div class="col-xs-12 f12 co-b6b6b6 pt-3 pr-5">{{service.summary}}</div>
            </div>
        </a>
        {% endfor %}

        {% if show_comingsoon %}
        <li class="list-group-item col-xs-12 pr-0 pl-0 over-flow-hide mb-15 animated fadeInUp" style="animation-delay: {{ last_delay }}s;-webkit-animation-delay: {{ last_delay }}s;">
            <div class="col-xs-12 text-center co-95989d h67 pt-5 pr">
                <span>更多供应商即将入驻......</span>
                <i class="fa fa-plug"></i>
            </div>
        </li>
        {% endif %}
    </ul>

</div>
{% endblock %}

{% block nav %}{% endblock %}